### PR TITLE
#108 Add eslint-config-spt

### PR DESCRIPTION
**Pull request by Andersos**
So I added eslint and [eslint-config-spt](https://github.com/schibsted/eslint-config-spt).
I'm unsure if we wanted to remove the jshint stuff. I can remove that if we want to.

We have 3 config files now:
[main](https://github.com/Andersos/unleash/blob/a23cdf09de074aa8ce88a980a6cc247688282b7d/.eslintrc)
[__ test__](https://github.com/Andersos/unleash/blob/a23cdf09de074aa8ce88a980a6cc247688282b7d/public/js/__tests__/.eslintrc)
[test](https://github.com/Andersos/unleash/blob/a23cdf09de074aa8ce88a980a6cc247688282b7d/test/.eslintrc)

I ignored some of the rules. Ideally we will remove the ignored rules over time but I dont want this pull request to be too big. Most of the changes in this pull request are only whitespace or removing unused variables.

### CODE REVIEW

**Comment by Andersos** [comment]
So looks like a bundle file is generated and Travis is linting that bundle. I'll just ignore the file.

**Comment by ivarconr** [comment]
great stuff. I will look at it tomorrow! And yes, we want to remove the
jshint stuff!

**Comment by Andersos** [comment]
It looks like the branch has conflicts. I'm unsure what it is about but I'll try and fix it

**Comment by Andersos** [comment]
Pulled in changes from upstream and fixed conflict. Closing this pull request in favor of https://github.com/finn-no/unleash/pull/111

**Pull request closed without merging**
