### PR TITLE
Add Unleash logo

### PR DESCRIPTION
**Pull request by Andersos**
So this is my take on a Unleash logo. Let me know what you think =)

unleash

### CODE REVIEW

**Comment by rubendw** [comment]
My first impression is that chains that are breaking have other connotations than that of unleashing something. 
"Oh, it broke" "Look at that poor quality chain". 

I am thinking more in the line of something like this: http://previews.123rf.com/images/sararoom/sararoom1305/sararoom130500029/19552759-illustration-of-Angry-cartoon-dog-Stock-Vector.jpg (with a pulled chain?)

**Comment by ivarconr** [comment]
I agree with @rubendw, is this somehting you can manage @Andersos ?

**Comment by Andersos** [comment]
So is the animal we want a dog? Dose it have to be angry or is that part of the feeling? =)

**Comment by rubendw** [comment]
For a logo to be stylistic enough, we might do it a bit complicated for ourself if it pictures a squirrel or a hedgehog in leashes, as a dog tugging the leash is a well known symbol. 
That said, a squirrel, frog, kangaroo or sloth in a leash would be cooler if it could be pulled off!
I feel a bit of anger (or at least some kind of danger involved) is needed for something to be unleashed.

http://themetamart.com/hearthstone/unleash_the_hounds.jpg

**Comment by torarnek** [comment]
My first thought was button that is used for launching rocket... 
image

**Comment by Andersos** [comment]
Haha, cool =)

**Comment by ivarconr** [comment]
Nice :)

**Comment by sveisvei** [comment]
skjermbilde 2016-04-20 kl 21 50 10

**Comment by sveisvei** [comment]
unleash

**Comment by sveisvei** [comment]
skjermbilde 2016-04-20 kl 22 00 49

**Comment by sveisvei** [comment]
skjermbilde 2016-04-20 kl 22 04 02

**Comment by sveisvei** [comment]
logo2

**Comment by ivarconr** [comment]
I think we should try to keep it as simple as possible. 

I like: 

skjermbilde 2016-04-20 kl 22 00 49

But could the flipper be one of the letters. Maybe instead of the 'l'? What do you think @sveisvei and @Andersos ?

**Comment by sveisvei** [comment]
logo3

**Comment by ivarconr** [comment]
I like the simplicity, but yes it still need some tweaking.

**Comment by sveisvei** [comment]
logo4

**Pull request closed without merging**
