### PR TITLE
Clearer colors

### PR DESCRIPTION
**Pull request by haakoneriksen**
commit messages should be pretty obvious

### CODE REVIEW

**Comment by Andersos** [comment]
Hey @haakoneriksen thanks for the pull request. Sorry for the colors being bad. This pull request gets a 👍 from me.
We are planning to rewrite the [admin ui](https://github.com/finn-no/unleash/milestones/Rewrite%20the%20admin-ui) and I will keep the colors in mind.

**Comment by haakoneriksen** [comment]
Yeah, @Andersos I like those toggles. I considered making some checkmark or X-es in CSS to make the shape clearer but if you're rewriting it I'm glad I didn't spend the time. 
If you're taking feature requests for the admin GUI, I'd like to submit the idea that it would be helpful to see the same feature in all environments. For example, I'd like to see that some feature is on in the "dev" environment, but off in "CI" and "prod" without having to visit three different web pages.

**Comment by Andersos** [comment]
I know @ivarconr has been talking about promoting toggles between environments so if we are going down that path (having Unleash know about different environments) then we might as well consider this use case. The promoting features is still on the idea board so not something I'm promising =)

**Comment by ivarconr** [comment]
we are working on a new UI but merging this for now as these colors are nice =)

**Pull request merged**
